<?php

namespace App\Database;

use App\Enums\DataTableColumnType;
use Illuminate\Database\Eloquent\Builder;

final class PostgresDatabaseDialect extends AbstractDatabaseDialect
{
    public function acquireIdentityMutex(array $keys): void
    {
        foreach ($keys as $key) {
            $this->connection->select(
                'SELECT pg_advisory_xact_lock(hashtext(?), hashtext(?))',
                ['puppetflow:identity', $key],
            );
        }
    }

    public function lockMailboxClaim(Builder $query): void
    {
        $query->lock('FOR UPDATE SKIP LOCKED');
    }

    public function jsonObjectIsNotEmpty(string $column): SqlExpression
    {
        $column = $this->wrap($column);

        return new SqlExpression(
            "jsonb_typeof(COALESCE({$column}::jsonb, '{}'::jsonb)) = 'object'"
            ." AND COALESCE({$column}::jsonb, '{}'::jsonb) <> '{}'::jsonb",
        );
    }

    public function jsonScalar(string $column, string $key): SqlExpression
    {
        return new SqlExpression(
            $this->wrap($column).'::jsonb ->> ?',
            [$key],
        );
    }

    public function createDataTable(string $table): void
    {
        $table = $this->identifier($table);
        $this->statement(
            "CREATE TABLE {$table} ("
            .'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            .'created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, '
            .'updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP'
            .')',
        );
    }

    public function dropDataTable(string $table): void
    {
        $this->statement('DROP TABLE IF EXISTS '.$this->identifier($table));
    }

    public function addDataTableColumn(string $table, string $column, DataTableColumnType $type): void
    {
        $sqlType = match ($type) {
            DataTableColumnType::STRING => 'TEXT',
            DataTableColumnType::NUMBER => 'DOUBLE PRECISION',
            DataTableColumnType::BOOLEAN => 'BOOLEAN',
            DataTableColumnType::DATETIME => 'TIMESTAMPTZ',
        };

        $this->statement(
            'ALTER TABLE '.$this->identifier($table)
            .' ADD COLUMN '.$this->identifier($column)." {$sqlType} NULL",
        );
    }

    public function renameDataTableColumn(string $table, string $from, string $to): void
    {
        $this->statement(
            'ALTER TABLE '.$this->identifier($table)
            .' RENAME COLUMN '.$this->identifier($from)
            .' TO '.$this->identifier($to),
        );
    }

    public function dropDataTableColumn(string $table, string $column): void
    {
        $this->statement(
            'ALTER TABLE '.$this->identifier($table)
            .' DROP COLUMN '.$this->identifier($column),
        );
    }
}
