import type { NodalEditorPaneProps } from '../NodalEditorPane.types';
import { useCanvasInteractions } from './useCanvasInteractions';
import { useCanvasTransformMode } from './useCanvasTransformMode';
import type { NodalGraphController } from './useNodalGraphController';
import { useNodalEditorEffects } from './useNodalEditorEffects';
import { useNodeActions } from './useNodeActions';
import { useNodeEditingContext } from './useNodeEditingContext';

type NodalInteractionsControllerProps = Pick<
    NodalEditorPaneProps,
    'flow' | 'graphContext'
> & {
    graphController: NodalGraphController;
};

// Combines canvas, node, keyboard, and clipboard interactions for the nodal editor.
export function useNodalInteractionsController({
    flow,
    graphContext = 'flow',
    graphController,
}: NodalInteractionsControllerProps) {
    const {
        activatePane,
        canvasMode,
        canvasRef,
        connectionDragRef,
        contextMenu,
        currentGraph,
        edges,
        finallyEnabled,
        getWorldPointFromClient,
        isActivePane,
        isAnotherPaneActive,
        knifeDragRef,
        lastPointerWorldRef,
        nodeDragRef,
        nodes,
        openNodeMenuId,
        pendingConnectionTarget,
        pendingEdgeInsertion,
        pendingNodePlacementRef,
        pickerOpen,
        readOnly,
        recordHistory,
        redoGraph,
        revealMiniMap,
        selectedNodeIds,
        selectionPointerRef,
        setConnectionDrag,
        setContextMenu,
        setEdgeDropTarget,
        setEditingNode,
        setEditingStickyNoteId,
        setEdges,
        setKnifeDrag,
        setNodes,
        setOpenNodeMenuId,
        setPendingConnectionTarget,
        setPendingEdgeInsertion,
        setPickerOpen,
        setSearch,
        setSelectedNodeIds,
        setSelectionBox,
        setViewport,
        toast,
        undoGraph,
        viewport,
        visibleNodes,
    } = graphController;
    // Pointer, drag, marquee and keyboard interactions only see drawn nodes (a disabled FINALLY
    // branch stays in state but must not be selectable). State updates go through setNodes updaters.
    const {
        setTransformMode,
        startMoveTransform,
        startSwapTransform,
        transformMode,
    } = useCanvasTransformMode({
        canvasMode,
        nodes: visibleNodes,
        readOnly,
        selectedNodeIds,
        lastPointerWorldRef,
        recordHistory,
        setContextMenu,
        setOpenNodeMenuId,
        setPickerOpen,
        setPendingConnectionTarget,
        setPendingEdgeInsertion,
    });
    const nodeActions = useNodeActions({
        canvasRef,
        nodes,
        edges,
        selectedNodeIds,
        pendingConnectionTarget,
        pendingEdgeInsertion,
        pendingNodePlacementRef,
        viewport,
        readOnly,
        recordHistory,
        setNodes,
        setEdges,
        setSelectedNodeIds,
        setEditingNode,
        setOpenNodeMenuId,
        setPendingConnectionTarget,
        setPendingEdgeInsertion,
        setPickerOpen,
        setSearch,
        toast,
    });
    const canvasInteractions = useCanvasInteractions({
        activatePane,
        canvasMode,
        canvasRef,
        connectionDragRef,
        edges,
        getWorldPointFromClient,
        knifeDragRef,
        lastPointerWorldRef,
        nodeDragRef,
        nodes: visibleNodes,
        onViewportPan: revealMiniMap,
        readOnly,
        recordHistory,
        selectedNodeIds,
        selectionPointerRef,
        setConnectionDrag,
        setContextMenu,
        setEdgeDropTarget,
        setEdges,
        setKnifeDrag,
        setNodes,
        setPendingConnectionTarget,
        setPendingEdgeInsertion,
        setPickerOpen,
        setSearch,
        setSelectedNodeIds,
        setSelectionBox,
        setViewport,
        viewport,
    });
    const editingContext = useNodeEditingContext({
        editingNode: graphController.editingNode,
        nodes,
        edges,
        currentGraph,
        finallyEnabled,
        flow,
        graphContext,
    });

    useNodalEditorEffects({
        canvasMode,
        contextMenu,
        editingNodeCurrent: editingContext.editingNodeCurrent,
        edges,
        getWorldPointFromClient,
        isActivePane,
        isAnotherPaneActive,
        lastPointerWorldRef,
        nodes: visibleNodes,
        openNodeMenuId,
        pasteNodesFromClipboard: nodeActions.pasteNodesFromClipboard,
        pendingConnectionTarget,
        pendingEdgeInsertion,
        pendingNodePlacementRef,
        pickerOpen,
        readOnly,
        redoGraph,
        selectedNodeIds,
        startMoveTransform,
        startSwapTransform,
        transformMode,
        undoGraph,
        copySelectedNodes: nodeActions.copySelectedNodes,
        deleteNodes: nodeActions.deleteNodes,
        duplicateSelectedNodes: nodeActions.duplicateSelectedNodes,
        toggleNodeDeactivation: nodeActions.toggleNodeDeactivation,
        setEditingStickyNoteId,
        setContextMenu,
        setEditingNode,
        setNodes,
        setOpenNodeMenuId,
        setPendingConnectionTarget,
        setPendingEdgeInsertion,
        setPickerOpen,
        setSearch,
        setSelectedNodeIds,
        setTransformMode,
    });

    return {
        ...canvasInteractions,
        ...editingContext,
        ...nodeActions,
    };
}

export type NodalInteractionsController = ReturnType<typeof useNodalInteractionsController>;
